options:
  port:
    type: string
    default: "8080"
    description: "Listen port passed to uvicorn."
  hostname:
    type: string
    default: "0.0.0.0"
    description: "Listen hostname passed to uvicorn."


