options:
  port:
    type: string
    default: "8080"
    description: "Listen port for the webserver."
  hostname:
    type: string
    default: "0.0.0.0"
    description: "Listen hostname for the webserver."


