#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

channel=$(config-get channel)

status-set maintenance "installing snap"

apt update
printf "Y\n8\n1\n" | apt install snapd  # set to Europe/Amsterdam

sleep 1

service snapd start
systemctl start snapd.service
alias snap=/usr/bin/snap

status-set maintenance "installing microsample snap"

snap install microsample --${channel}

status-set active

