#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

A=$(snap info microsample | grep -c 'installed')
if [[ $A -ne 1 ]]
then
  status-set maintenance "installing microsample snap"
  snap install microsample --edge;
fi

status-set active

